### ISSUE TITLE
ToDo back

### ISSUE THREAD

**Issue by Motzee** [Motzee/node-events#1]
Reste à faire côté back :
- [ ] système de réception via POST des données de formulaire de ajout/
- [ ] système de réception via POST des données de formulaire de auth/
- [ ] |-> inscription des données dans une BDD sql
- [ ] |-> module d'authentification
- [ ] Récupération de données dans une BDD sql pour desservir index/
- [ ] système de session utilisateur (avec connexion et déconnexion)
- [x] rajout d'une mustache date à prévoir
- [ ] création d'une BDD sql avec deux tables events et users
