### ISSUE TITLE
ToDo front

### ISSUE THREAD

**Issue by Motzee** [Motzee/node-events#2]
Reste à faire côté front :

- [ ] Création de 2 pages à formulaire login/ et signin/
- [ ] Ajout d'un champ date dans ajout/
- [ ] Ajout d'une sortie en mustache de date sur index/
